### ISSUE TITLE
fix the need to have a myRad and mydegree

### ISSUE THREAD

**Issue by yakir12** [yakir12/UnitfulAngles.jl#1]
In order not to overwrite the `rad` and `°` units from `Unitful.jl`, I called my radians and degrees `myRad` and `my°`. Ugly. How can I fix this?
I didn't base my angular system on the one already provided in `Unitful.jl` because tons of the units here can be expressed as a rational number of the full turn. `Unitful.jl` approach was to base the angles on radians. While that makes total sense, it feels like a shame to lose accuracy by doing the same here. Any input from @ajkeller34 would be appreciated!

**Comment by yakir12** [comment]
Fixed this now, after discussions in [discourse](https://discourse.julialang.org/t/ann-unitfulangles-a-unitful-units-package-for-angles/5065/12).

**Comment by waldyrious** [comment]
For future reference, the fix was in commit 138716e75.

(btw, I would suggest using PRs instead of direct commits even if you're the author of the repo, because it facilitates cross-referencing, auto-closing of issues, pre-merge testing, comment threads, etc.)
