### ISSUE TITLE
Cannot add UnitfulAngles as package in Julia 1.0.3?

### ISSUE THREAD

**Issue by AstroWanders** [yakir12/UnitfulAngles.jl#19]
Hello,

I recently updated from Julia 1.0.2 to 1.0.3 and am finding that I cannot add UnitfulAngles? Is there a compatibility problem?

I started this [thread](https://discourse.julialang.org/t/unitfulangles-error-with-julia-1-0-3/21760) on the Julia Discourse, however I haven't gotten helpful comments. 

Thank you!

**Comment by yakir12** [comment]
Hmm, it works for me, but I'm on julia 1.1.0.

Can you paste the error message you get from:
```julia
]add UnitfulAngles
```

**Comment by yakir12** [comment]
Hi @AstroWanders,
I think I fixed the issue now. Thanks for detecting it. Could you please try adding UnitfulAngles again and let me know if it worked? 
Thanks!

**Comment by waldyrious** [comment]
@yakir12 I suppose #18 now obsolete, then, since its changes have been redone in ccd8a82, right?

**Comment by yakir12** [comment]
Ha, that is correct...

**Comment by AstroWanders** [comment]
Thank you @yakir12! I added UnitfulAngles in v1.1.0

**Comment by yakir12** [comment]
Great, closing this now.
