### ISSUE TITLE
Release version 0.6.1

### ISSUE THREAD

**Issue by m-wells** [yakir12/UnitfulAngles.jl#25]
When the compat helper merge #24 happened the project version remained at 0.6.0.  We need to change the Project version to 0.6.1 and register with general.

You can see for yourself [here](https://github.com/JuliaRegistries/General/blob/master/U/UnitfulAngles/Compat.toml) that the register thinks that UnitfulAngles is only compatible with Unitful 0.16 which is several versions out of date.

**Comment by yakir12** [comment]
@JuliaRegistrator register

**Comment by yakir12** [comment]
Thanks for this! 
I'm closing it now because it seems your suggestion worked. Please feel free to reopen if this didn't work out for you.
