### ISSUE TITLE
Error in example: no `rad` or `°`

### ISSUE THREAD

**Issue by cmichelenstrofer** [yakir12/UnitfulAngles.jl#31]
[This example](https://github.com/yakir12/UnitfulAngles.jl#special-features) does not run because `rad` and `°` are not defined in UnitfulAngles. 

```Julia
julia> import UnitfulAngles: °, rad, octant
WARNING: could not import UnitfulAngles.° into Main
WARNING: could not import UnitfulAngles.rad into Main
```

The package uses the definitions of radians and degrees from Unitful.jl (I see there is some history, with these originally redefined in UnitfulAngles). But instead of importing these units it always uses them through u-strings. I think it would make sense to do 
```Julia
import Unitful: rad,  °
```
That way UnitfulAngles.jl includes these angles without users having to import them separately from Unitful. Note that this does not cause any conflicts, the `rad` and `°` would still be the ones from Unitful (check using @which) and not a redefinition (Julia is awesome!). 

I would be willing to make these changes as PR if @yakir12  you agree.

**Comment by cmichelenstrofer** [comment]
I would also add `import Dates` in the last example. With these changes if someone runs all the code blocks in order they will get the shown outputs.

**Comment by yakir12** [comment]
Yes please! Pr super welcome!

**Comment by cmichelenstrofer** [comment]
Done! #32 is ready for your review.
