### ISSUE TITLE
prefer exact conversion factors

### ISSUE THREAD

**Issue by MarkNahabedian** [yakir12/UnitfulAngles.jl#36]
Maybe the various angle measurements should be expressed in degrees rather than radians since that at leat allows the possibility for exact arithmetic rather than forcing the user to use inexact real numbers too soon.

**Comment by cmichelenstrofer** [comment]
All other units other than degrees, radians, and diameterPart are defined based on turn and conversion between them is already exact. Conversion between radians and diameterPart is exact too. This inexact conversion only comes about when converting between ° and one of these other units based on turn.

The only change required would be to define the `turn` as `360°` instead of `2π rad`.

**Comment by cmichelenstrofer** [comment]
e.g. right now 
```julia
julia> uconvert(u"hexacontade", 360u"°")
60.00000000000001 hexacontade
```

using degrees to define the turn:
```julia
julia> uconvert(ua"hexacontade", 360ua"°")
60//1 hexacontade
```

**Comment by MarkNahabedian** [comment]
If a turn is a single full circle (360 degrees or 2pi radians) then I think it should be the base/default unit for angles against which the other units are defined.

**Comment by cmichelenstrofer** [comment]
I can see why you would want that... e.g. when doing mixed unit operations promote using exact conversion (if possible). But the way Unitful treats angles (non-dimensional) it is important for the radian to be the unit equivalent to `1`. And actually, the radian is defined as `1` in Unitful itself. So all other units of angle need to be defined in terms of it. The only possible slight improvement I can see is defining the turn in terms of degrees.

**Comment by MarkNahabedian** [comment]
Thanks.  So switching from radians would be an incompatible change?

I suppose one could define a new dimension for angles that was based on full circles (is that what a turn is?).  I think that would require that the unit names not collide with existing angle units though.

**Comment by cmichelenstrofer** [comment]
> So switching from radians would be an incompatible change?

Yes

>  full circles (is that what a turn is?)

Yes

We should still change turn to be defined based on degrees (or vice versa) so that any explicit conversion (i.e. using `uconvert`) is exact whenever possible. Implicit promotions (e.g. due to mixed unit arithmetics) would still convert back to radians.
